version = 1

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "python"
dependency_file_paths = [
  "requirements.txt"
]

  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_length=79
  type_checker = "mypy"

[[transformers]]
name = "isort"

[[transformers]]
name = "black"

[[transformers]]
name = "autopep8"

[[transformers]]
name = "yapf"

[[transformers]]
name = "ruff"
