[build-system]
requires = ["setuptools>=65.6.3"]
build-backend = "setuptools.build_meta"

[project]
name = "sclogging"
version = "0.73"
description = "A Python module (with the help of coloredlogs) to add color to logs."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "dynaconf~=3.1.9",
    "colorama~=0.4.5",
    "coloredlogs~=15.0.1",
    "PyInputPlus~=0.2.12",
    "setuptools~=65.6.3",
]

[project.urls]
"Homepage" = "https://github.com/sshimek42/sclogging"
"Documentation" = "https://sclogging.readthedocs.io/"